import type { Knex } from "knex";

/**
 * password_resets: one row per forgot-password request. The secret is a typed 6-digit code (ADR 0017),
 * generated by the worker at send time and stored only as HMAC-SHA256(OTP_PEPPER, code) hex, so the table
 * mirrors registration_challenges (code_hash + attempts). A token table, not a business table: no
 * `deleted_at`, purged 30 days after `created_at`.
 *
 * No unique index on `code_hash`: a 6-digit code is not globally unique and the lookup is by user
 * (email -> live user -> latest open row FOR UPDATE), never by hash.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
      CREATE TABLE password_resets (
          id             BIGSERIAL PRIMARY KEY,
          user_id        BIGINT      NOT NULL,
          code_hash      CHAR(64)    NULL,
          attempts       SMALLINT    NOT NULL,
          expires_at     TIMESTAMPTZ NULL,
          used_at        TIMESTAMPTZ NULL,
          invalidated_at TIMESTAMPTZ NULL,
          created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

          CONSTRAINT fk_password_resets_user_id
              FOREIGN KEY (user_id) REFERENCES users (id),
          CONSTRAINT chk_password_resets_code_sent CHECK ((code_hash IS NULL) = (expires_at IS NULL)),
          CONSTRAINT chk_password_resets_attempts CHECK (attempts BETWEEN 0 AND 5),
          CONSTRAINT chk_password_resets_code_hash_hex CHECK (
              code_hash IS NULL OR code_hash ~ '^[0-9a-f]{64}$'
          ),
          CONSTRAINT chk_password_resets_used_after_sent CHECK (used_at IS NULL OR code_hash IS NOT NULL),
          CONSTRAINT chk_password_resets_single_end CHECK (used_at IS NULL OR invalidated_at IS NULL)
      );
  `);

  // Covers fk_password_resets_user_id. reset-password reads the latest open row:
  //   SELECT <PASSWORD_RESET_COLUMNS> FROM password_resets
  //   WHERE user_id = $1 AND used_at IS NULL AND invalidated_at IS NULL
  //   ORDER BY created_at DESC LIMIT 1 FOR UPDATE
  // forgot-password / reset also invalidate open rows:
  //   UPDATE password_resets SET invalidated_at = now()
  //   WHERE user_id = $1 AND used_at IS NULL AND invalidated_at IS NULL
  await knex.raw(`
      CREATE INDEX idx_password_resets_user_id_created_at ON password_resets (user_id, created_at DESC);
  `);

  // Worker purge: DELETE ... WHERE id IN
  //   (SELECT id FROM password_resets WHERE created_at < now() - interval '30 days' LIMIT $1)
  await knex.raw(`
      CREATE INDEX idx_password_resets_created_at ON password_resets (created_at);
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`DROP TABLE IF EXISTS password_resets;`);
}
