import type { Knex } from "knex";

/**
 * registration_challenges: proof of email ownership before an account exists (ADR 0006).
 * The 6-digit code is generated by the worker at send time and stored only as
 * HMAC-SHA256(OTP_PEPPER, code) hex. A token table, not a business table: no `deleted_at`, purged 24 h
 * after `created_at`. No FK to users — the account does not exist yet.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
      CREATE TABLE registration_challenges (
          id             BIGSERIAL PRIMARY KEY,
          email          CITEXT      NOT NULL,
          code_hash      CHAR(64)    NULL,
          attempts       SMALLINT    NOT NULL,
          expires_at     TIMESTAMPTZ NULL,
          consumed_at    TIMESTAMPTZ NULL,
          invalidated_at TIMESTAMPTZ NULL,
          created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

          CONSTRAINT chk_registration_challenges_code_sent CHECK (
              (code_hash IS NULL) = (expires_at IS NULL)
          ),
          CONSTRAINT chk_registration_challenges_attempts CHECK (attempts BETWEEN 0 AND 5),
          CONSTRAINT chk_registration_challenges_code_hash_hex CHECK (
              code_hash IS NULL OR code_hash ~ '^[0-9a-f]{64}$'
          ),
          CONSTRAINT chk_registration_challenges_single_end CHECK (
              consumed_at IS NULL OR invalidated_at IS NULL
          ),
          CONSTRAINT chk_registration_challenges_email_length CHECK (length(email) <= 254)
      );
  `);

  // register/complete reads the latest open challenge:
  //   SELECT <REGISTRATION_CHALLENGE_COLUMNS> FROM registration_challenges
  //   WHERE email = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
  //   ORDER BY created_at DESC LIMIT 1 FOR UPDATE
  // register/start invalidates open challenges for the same email:
  //   UPDATE registration_challenges SET invalidated_at = now()
  //   WHERE email = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
  await knex.raw(`
      CREATE INDEX idx_registration_challenges_email_open ON registration_challenges (email, created_at DESC)
          WHERE consumed_at IS NULL AND invalidated_at IS NULL;
  `);

  // Worker purge: DELETE ... WHERE id IN
  //   (SELECT id FROM registration_challenges WHERE created_at < now() - interval '24 hours' LIMIT $1)
  await knex.raw(`
      CREATE INDEX idx_registration_challenges_created_at ON registration_challenges (created_at);
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`DROP TABLE IF EXISTS registration_challenges;`);
}
